name: Example workflow_dispatch

on:
  workflow_dispatch: # referred to by the filename
    inputs:
      name:
        description: Whom to greet
        required: true
      ref:
        name:
          description: Ref the event is for
          required: true

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'Hello ${{github.event.inputs.name}}!'
    - run: echo 'dispatched for ${{github.event.inputs.ref}}'
