name: Example repository_dispatch

on:
  repository_dispatch:
    types: [Example repository_dispatch] # the name here is referred to by the dispatch

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'Hello ${{github.event.client_payload.name}}!'
    - run: echo 'dispatched for ${{github.event.client_payload.ref}}'
